resources:
- name: source-code
  type:  git
  check_every: 5m
  source: 
    uri: https://github.com/hygl/spring-boot-concourse-openfaas
jobs: 
- name: build
  plan:
    - get: source-code
      trigger: true
    - task: test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: 
            repository: maven
            tag: 3.6-jdk-11
        inputs: 
          - name: code
        outputs:
          - name: build
        caches:
          - path: code/.m2
        run:
          path: sh
          args:
          - -c
          - mvn -f code/spring-boot/pom.xml test -Dmaven.repo.local=code/.m2
            # cp code/spring-boot/target/*.jar build/runner.jar 
resource_types:
  - name: openfaas
    type: docker-image
    source:
      repository: timotto/concourse-openfaas-resource